Section-1 Markov Decision Process

A Markov Decision Process(MDP) is a way to describe a problem where an agent(like a robot, game player, or AI), is inside an environment. Which takes actions, gets rewards or punishments and wants to make the best decisions over time. The main goal of an MDP is to maximize long-term reward. MDPs are foundation of Reinforcement Learning.

Five components: An MDP is defined by a 5-tuple:(S, A, P, R, γ). 1.States(S): A state tells us where the agent is right now. It is a complete description of the current situation. The agent always knows its current state.Ex: robot position in a grid (0,0), (0,1), (1,0)...                 2.Action(A): All possible actions the agent can take. From each state the agent chooses one action. Ex: Up, down, left, right.         3.Transition Probability(P): Probability of moving to the next state after taking an action. P(s'|s, a).Where s'= Probability of reaching next state s', a= action, s= state Ex: 80% chance it moves right, 20% chance it slips.  4. Reward(R): Reward is instand feedback from environment, it tells weather the action is good or bad. Ex: Moves one step-> -1 reward, reaches goal-> +10 reward, fall into trap-> -10 reward.     5. Discount Factor(γ): Discount factor tells How much we care about future rewards. It ranges value between 0 & 1. γ=0-> only immediate reward matters, γ=1->future reward matters same as present, γ=0.9-> future reward matters but a little less. So immediate rewards are more important than future ones.

Markov property: The markov property says, the future depends only on the present not the past. Which means, the agent does not need to remember everything, the current state has all the information. Ex: it a robot is at (2,2), it does not matter how it reaches there, only its current position matters. So mathematically: P(St+1​∣St​,at​)

Policy vs Value function: A policy(pi) tells what action to take in each state. Its like a rule book which guides the agent. Ex: If at (0,0)-> move right, If at(0,1)-> move down . So pi(s)=a. Value function(v) A value function tells how good a state or action is, it tells how much reward we can expect in the future. Ex: state(1,1) has value = 5, state(2,2) has value = 8 , This means (2,2) is better than (1,1). Reward vs Return: Reward is the immediate value, given after one action. Ex: move-> -1, goal-> +10. Return is the total reward collected overtime, it includes future rewards. So Return= reward now+discounted future rewards.

Robot Grid world- Scenario
A robot moves inside a grid. The robot receives a reward when it reaches the goal. The robot receives a penalty for each move. The objective of the robot is to reach the goal with maximum total reward.
States represent the current position of the robot in the grid. Each cell of the grid is a state. Ex: (0,0), (0,1),  (1,0), (1,1) etc. 
The robot can take Up, down, Left, Right actions. Reaching the goal gives a positive reward(+10), Each movement gives a small penalty(-1), falling into trap gives a negative reward(-10).
This is an Episodic task because the episode ends when, the robot reaches the goal or the robot falls into a trap. 
The deterministic policy always selects the same action for a given state. Ex: If the robot is not in the last column, move right, Tf the robot is in the last column, move down.

Numerical Exercise: Given Discount factor(γ) = 0.9, Rewards = [5, 2, 1]. Formula to  return: G=R0 + γR1 + γ^2 R2

In [4]:
gamma = 0.9
rewards = [5, 2, 1]
G = rewards[0] + gamma * rewards[1] + (gamma ** 2) * rewards[2]
G

7.609999999999999

The return is calculated as: G = 5+(0.9* 2) + (0.9^2 * 1)
G=5+1.8+0.81
G=7.609
Therefore the total return G is 7.609

Section 2: Python programming basic

In this we generate numbers from 1-20, then we extract only the even numbers using: loop, list comprehension. We use a loop to go through numbers from 1-20, for each number we check if it is even. If the number is divisible by 2, it is an even number. We store all even numbers in a list.

In [5]:
even_numbers = []
for i in range(1, 21):
    if i % 2 == 0:
        even_numbers.append(i)
even_numbers

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

List comprehension is a shorter way to write a loop. It performs the same task in a single line.

In [6]:
even_numbers = [i for i in range(1, 21) if i%2 == 0]
even_numbers

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

Function to compute mean of a list:
Mean is the average value of a list of numbers. Mean is calculated by dividing the sum of values by the number of values. To compute the mean: 1. We take a list of numbers, 2. Add all the numbers, 3. Count how many numbers are present. 4.Divide the sum by the count. 5.Return the result.

In [7]:
def calculate_mean(numbers):
    total = sum(numbers)
    count = len(numbers)
    mean = total / count
    return mean

In [8]:
values = [10, 20, 30, 40]
calculate_mean(values)

25.0

Create NumPy arrays and compute statistics: NumPy is used for numerical operations. It allows us to perform mathematical calculations easily.

In [9]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

Statistics using numpy

In [10]:
np.mean(arr)
np.max(arr)
np.min(arr)
np.std(arr)

14.142135623730951

Create a pandas dataframe and filter rows based on conditions.
Pandas is used to work with tabular data. A dataframe looks like a table with rows and columns. Steps: Import pandas, 2.Create data using a dictionary, 3.Convert it into a dataframe, 4.Filter rows based on a condition.

In [11]:
import pandas as pd
data = {
    "Name":["A", "B", "C", "D"],
    "Marks":[60, 80, 45, 90]
}
df = pd.DataFrame(data)
df

c:\Users\Humera Siddiqua\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\Humera Siddiqua\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

  Name  Marks
0    A     60
1    B     80
2    C     45
3    D     90

Filtering rows based on function

In [12]:
df[df["Marks"] >= 60]

  Name  Marks
0    A     60
1    B     80
3    D     90

Debugging the code:
The given code contains a syntax error. Given code: for i in range(5)
print(i)
Problems:1. Missing colon(:) after the for loop, 2.Incorrect indentation.
Correct code:

In [13]:
for i in range(5):
    print(i)

0
1
2
3
4

Section-3 Decision Tree
Decision Trees are used to solve- classification problems, Regression problems. A Decision tree is a machine learning model that makes decisions using questions. It works like a flowchart: Each question splits the data, Each answer leads to another question or a final decision. Decision trees are mainly used when we want- Easy interpretation, clear decision rules.

Entropy measures how mixed or impure the data is. If the data is- Pure(all same class)-> entropy is 0, mixed(many classes)-> entropy is high.
Information gain tells us How much entropy is reduced after splitting the data. The split with the highest information gain is chosen.

Decision tree overfit when they grow too deep. This happens because- The tree learns noise in the training data, it memorizes data instead of learning patterns, it performs well on training data but poorly on new data. Overfitting can be reduced by- Limiting tree depth, using max_depth, pruning the tree.

The best root node is the feature that splits the data most clearly. We choose the feature that- separates classes well, Creates purer child nodes, has high information gain.

Python practice: We need to train a Decision tree model and make predictions. Steps: 1.Importing required libraries, 2.Creating a small dataset, 3.Training a DecisionTreeClassifier with max_depth=3, 4.Generating predictions.

In [14]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

In [15]:
data = {
    "Age": [22, 25, 47, 52, 46, 56],
    "Income":[20000, 30000, 80000, 90000, 70000, 100000],
    "Buy":[0, 0, 1, 1, 1, 1]
}
df = pd.DataFrame(data)
df

   Age  Income  Buy
0   22   20000    0
1   25   30000    0
2   47   80000    1
3   52   90000    1
4   46   70000    1
5   56  100000    1

In [16]:
X = df[["Age", "Income"]]
y = df["Buy"]

In [17]:
model = DecisionTreeClassifier(max_depth=3)
model.fit(X, y)

DecisionTreeClassifier(max_depth=3)

In [18]:
predictions = model.predict(X)
predictions

array([0, 0, 1, 1, 1, 1], dtype=int64)

The model predicts weather a person will buy or not. 0 means no, 1 means yes. The predictions are based on learned decision rules.

Section-4 K-Means clustering:
K-Means clustering is an unsupervised learning algorithm. This means, there are no labels given, the algorithm groups data by itself, It finds without knowing the correct answers.

K-means clustering works in the following steps: 1. Choose the number of clusters(k), 2.Randomly select k points as initial centrids, 3.Assign each data point to the nearest centroid, 4.Recalculate the centroid of each clusters, 5.Repeat steps 3 and 4 until centroids do not change.

Feature scaling is important because K-means uses distance. If features are on different scales- Large value dominate the distance, Small values become less important. 
Scaling ensures all features contribute equally, clusters are formed correctly.

Inertia is the sum of squared distances between data points and their cluster centroids. Low inertia means- Points are close to centroids, better clustering.

The elbow method is used to find the best value of K. Steps: 1.Run K-means for different values of k, 2.Calculate inertia for each step. 3.Plot k vs inertia, 4.Choose the k where inertia stops decreasing sharply. This point looks like an elbow.

Python practice: applying k-means algorithm using python. steps: 1.Import required libraries, 2.Create a dataset, 3.Apply feature scaling, 4.Fit K-means with k=3, 5.Extract cluster labels.

In [19]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [20]:
data = {
    "Age": [22, 25, 47, 52, 46, 56],
    "Income": [20000, 30000, 80000, 90000, 70000, 100000]
}
df = pd.DataFrame(data)
df

   Age  Income
0   22   20000
1   25   30000
2   47   80000
3   52   90000
4   46   70000
5   56  100000

Before applying K-means we scale the data. This ensures all features are on the same scale.

In [21]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)
scaled_data

array([[-1.48038203, -1.50699304],
       [-1.25066757, -1.1721057 ],
       [ 0.43390508,  0.50233101],
       [ 0.8167625 ,  0.83721836],
       [ 0.35733359,  0.16744367],
       [ 1.12304843,  1.1721057 ]])

In [22]:
KMeans = KMeans(n_clusters=3, random_state=42)
KMeans.fit(scaled_data)

KMeans(n_clusters=3, random_state=42)

In [23]:
cluster_labels = KMeans.labels_
cluster_labels

array([1, 1, 2, 0, 2, 0])

We now add the clusters labels to the original dataset.

In [24]:
df["Cluster"] = cluster_labels
df

   Age  Income  Cluster
0   22   20000        1
1   25   30000        1
2   47   80000        2
3   52   90000        0
4   46   70000        2
5   56  100000        0

Each datapoint is assigned a cluster label:Cluster 0, Cluster 1, Cluster 2. This labels indicates which group each data point belongs to.

Section-5: Applied Scenario. 
We are given customer data containing: age, income, spending score. The task is to choose the most suitable method among: Decision tree, K-means, MDP.

Customer segmentation means grouping customers based on similar behaviour. The best method for customer segmentation is k-means clustering. K-means is chosen because: 1.The data does not have labels, 2.We want to group customers based on similarity, 3.K-means is an unsupervised learning algorithm, 4.It is commonly used for customer segmentation problems, 5.It works well with numerical features like Age, Income, and Spending Score.

Decision Tree require labeled data. In customer segmentation, we do not know the target class, there is no predefined output. Therefore, Decision tree are not suitable for this task.
MDP is used for sequential decision making problems. Ex of MDP: Robot navigation, game playing, reinforcement learning tasks. Customer segmentation is not a sequential decision problem. Therefore MDP is not appropriate here.

For customer segmentation using age, income, and spending score- K-means is the most suitable method.

If recommendations depend on previous actions and customer responses, then the problem becomes a sequential decision making problem. In this case the correct concept is: MDP. MDP applies because: 1.The system makes decisions step by step, 2.Each recommendation affects the next state, 3.The goal is to maximize long-term reward, 4.Customer behavior changes over time.